<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * MovieListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieListRepository extends EntityRepository
{
    public function findPreviousMovieList($currentMovieListId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT ml
            FROM AppBundle:MovieList ml
            WHERE ml.id < :currentMovieListId
            ORDER BY ml.id DESC'
        )->setParameter('currentMovieListId', $currentMovieListId);

        $movieList = $query->setMaxResults(1)->getOneOrNullResult();

        return $movieList;
    }

    public function findNextMovieList($currentMovieListId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT ml
            FROM AppBundle:MovieList ml
            WHERE ml.id > :currentMovieListId
            ORDER BY ml.id DESC'
        )->setParameter('currentMovieListId', $currentMovieListId);

        $movieList = $query->setMaxResults(1)->getOneOrNullResult();

        return $movieList;
    }
}
